### PR TITLE
Support "long" predicateTypes.

### PR DESCRIPTION
**Pull request by JavadocMD**
Patch for Issue #142

### CODE REVIEW

**Comment by dqian96** [comment]
+1 on this

**Comment by mdp0023** [comment]
+1

**Comment by Gouarvg2** [comment]
+1

**Comment by edwardjmoore** [comment]
+1

**Comment by gwgcirco** [comment]
Fixes the issue

+1

**Comment by bjhawk** [comment]
+1

**Comment by wsrob** [comment]
+1

**Comment by agentdanger** [comment]
+1 this fixes the issue.

**Comment by kaogilvie** [comment]
+1

**Comment by am2222** [comment]
@fgregg Any chances this can be merged please? There are a few PRs which updates this package to be usable for the latest versions of the census updates.

**Comment by lazarust** [comment]
+1 This would be really nice to get merged ASAP

**Comment by HungMingTseng** [comment]
+1 Is it possible do a basic query from ACS5 now?
Mine still shows KeyError: 'long'
Thanks for helping

**Pull request merged**
