### PR TITLE
Added method to query a tables list

### PR DESCRIPTION
**Pull request by palewire**

### CODE REVIEW

**Comment by palewire** [comment]
IMHO, one weakness of this library is it assumes the user knows the code of the table they want to query. I often don't. This patch is a first step at trying to surface more of the metadata about tables and fields in the Census API in this library. 

Run this and get a list of all the tables offered by the survey.

```python
c.acs5.tables()
```

**Comment by fgregg** [comment]
Looking good. I'll take another look tomorrow, when I'm less bleary eyed.

What do you see as possible future steps forward to helping users find the right variable?

**Comment by palewire** [comment]
For one: Return a list of all variables on the table.

**Comment by knaaptime** [comment]
fwiw, [cenpy](https://github.com/ljwolf/cenpy) has this functionality

**Comment by fgregg** [comment]
Thanks, Ben!

**Pull request merged**
