### PR TITLE
Provide support for ACS5 Subject Tables

### PR DESCRIPTION
**Pull request by grahamalama**
This would allow support for the ACS5 Subject Tables via the `https://api.census.gov/data/<year>/acs/acs5/subject/` endpoints.

### CODE REVIEW

**Comment by grahamalama** [comment]
👋 Opened this PR a while ago, and I see that there's a MC. Should I bother updating this PR to fix it, or just close it?

**Comment by MaxGhenis** [comment]
cc @detinator10 who commented in #90 that he's gotten this working (presumably without the merge conflicts, which is just in the README)

**Comment by Detinator10** [comment]
@MaxGhenis I just created a new pull request with my code, hope that helps

**Comment by grahamalama** [comment]
Closing in favor of the discussion around #90 and #92

**Pull request closed without merging**
